### ISSUE TITLE
执行run_tests报错，请问怎么解决？

### ISSUE THREAD

**Issue by dickyxiao** [defnngj/pyrequest#3]
报错内容：
“””
Traceback (most recent call last):
  File "F:\Python脚本\pyrequest\interface\add_event_test.py", line 24, in test_add_event_all_null
    self.result = r.json()
  File "D:\python\lib\site-packages\requests\models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\python\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\python\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
“””
可能是json解析问题？

**Comment by defnngj** [comment]
接口返回的数据不是json格式，用```r.text```查看。

```python
r = requests....
print(r.text)
```
